language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.gradle
script: ./gradlew test

deploy:
  - provider: script
    script: bash khakis/bin/release.sh
    skip_cleanup: true
    on:
      tags: true
